apiVersion: apps/v1
kind: Deployment
metadata:
  name: contacts-app
spec:
  selector:
    matchLabels:
      app: contacts-app
  template:
    metadata:
      labels:
        app: contacts-app
    spec:
      containers:
        - name: contacts-app
          image: registry.digitalocean.com/invyce-images/contacts-service:c3f0a9b
          resources:
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
            - containerPort: 3333

---
# k8s service for this micro-service

apiVersion: v1
kind: Service
metadata:
  name: contacts-http
spec:
  selector:
    app: contacts-app
  ports:
    - port: 80
      targetPort: 3333

---

# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: contacts-vs
spec:
  gateways:
    - invyce-staging-gateway
  hosts:
  - "staging.invyce.com"
  http:
  - name: 'contacts-endpoint'
    match:
    - uri:
        prefix: '/contacts'
    route:
    - destination:
        host: contacts-http

