apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
spec:
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users-app
        image: registry.digitalocean.com/invyce-images/users-service:af90f94
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3334

---

apiVersion: v1
kind: Service
metadata:
  name: users-http
spec:
  selector:
    app: users-app
  ports:
  - port: 80
    targetPort: 3334

---

# See more at https://istio.io/docs/reference/config/networking/virtual-service/
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: users-vs
spec:
  gateways:
    - invyce-staging-gateway
  hosts:
  - "staging.invyce.com"
  http:
  - name: 'users-endpoint'
    match:
    - uri:
        prefix: '/users'
    route:
    - destination:
        host: users-http

