apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-app
spec:
  selector:
    matchLabels:
      app: users-app
  template:
    metadata:
      labels:
        app: users-app
    spec:
      containers:
      - name: users-app
        image: registry.digitalocean.com/invyce-images/users-service:0.0.3
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3334

---

apiVersion: v1
kind: Service
metadata:
  name: users-http
spec:
  selector:
    app: users-app
  ports:
  - port: 80
    targetPort: 3334
