export default [
  {
    name: 'Milk Pack',
    purchasePrice: 1200,
    sellPrice: 1500,
    brand: 'Nestle',
    category: 'Milk',
    status: 'Active',
  },
  {
    name: 'Lays',
    purchasePrice: 200,
    sellPrice: 500,
    brand: 'Nestle',
    category: 'Milk',
    status: 'Deactive',
  },
  {
    name: 'Paint',
    purchasePrice: 1700,
    sellPrice: 1900,
    brand: 'Nestle',
    category: 'Milk',
    status: 'Active',
  },
  {
    name: 'Water',
    purchasePrice: 200,
    sellPrice: 250,
    brand: 'Nestle',
    category: 'Milk',
    status: 'Active',
  },
  {
    name: 'Laptop',
    purchasePrice: 11200,
    sellPrice: 12500,
    brand: 'Nestle',
    category: 'Milk',
    status: 'Active',
  },
];
