export const packages = [
  {
    name: 'startup',
    invoices: 5,
    lineItems: 10,
    users: 2,
    contacts: 10,
    threshold: 75,
    items: 20,
    rbac: true,
    categories: false,
    integrations: ['slack'],
  },
  {
    name: 'small-business',
    invoices: 25,
    lineItems: 100,
    users: 15,
    contacts: 50,
    threshold: 250,
    items: 100,
    rbac: true,
    categories: false,
    integrations: ['slack'],
  },
  {
    name: 'growing-business',
    invoices: 200,
    lineItems: 100,
    users: 30,
    contacts: 200,
    threshold: 500,
    items: 300,
    rbac: true,
    categories: false,
    integrations: ['slack'],
  },
];
