export * from './lib/send-email.module';

export const SEND_OTP = 'SEND_OTP';
export const SEND_FORGOT_PASSWORD = 'SEND_FORGOT_PASSWORD';
export const SEND_INVITATION = 'SEND_INVITATION';
export const CREATE_ATTACHMENT = 'CREATE_ATTACHMENT';
export const INIT_ACCOUNTS = 'INIT_ACCOUNTS';
export const SEND_PDF_MAIL = 'SEND_PDF_MAIL';
export const CONTACT_CREATED = 'CONTACT_CREATED';
export const USER_CREATED = 'USER_CREATED';
export const ORGANIZATION_CREATED = 'ORGANIZATION_CREATED';
export const TRAIL_STARTED = 'TRAIL_STARTED';
export const PASSWORD_UPDATED = 'PASSWORD_UPDATED';
export const SUSPEND_ACCOUNT = 'SUSPEND_ACCOUNT';
export const CHANGE_EMAIL_OTP = 'CHANGE_EMAIL_OTP';
export const CHANGE_PASSWORD_OTP = 'CHANGE_PASSWORD_OTP';
export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const BILL_CREATED = 'BILL_CREATED';
export const BILL_UPDATED = 'BILL_UPDATED';
export const INVOICE_CREATED = 'INVOICE_CREATED';
export const INVOICE_UPDATED = 'INVOICE_UPDATED';
export const TRAIL_EXPIRING_IN_5_DAYS = 'TRAIL_EXPIRING_IN_5_DAYS';
export const TRAIL_EXPIRING_IN_2_DAYS = 'TRAIL_EXPIRING_IN_2_DAYS';
export const TRAIL_EXPIRING_IN_24_HOURS = 'TRAIL_EXPIRING_IN_24_HOURS';
export const DID_NOT_SEND_INVOICE_IN_LAST_7_DAYS =
  'DID_NOT_SEND_INVOICE_IN_LAST_7_DAYS';
