export enum ReactQueryKeys {
  CONTACTS_KEYS = 'APP/CONTACT_KEYS',
  ITEMS_KEYS = 'APP/ITEM_KEYS',
  PAYMENTS_KEYS = 'APP/PAYMENT_KEYS',
  ACCOUNTS_KEYS =  'APP/ACCOUNT_KEYS',
  TRANSACTION_KEYS = 'APP/TRANSACTION_KEYS',
  BANK_KEYS = 'APP/BANK_KEY'
}
